openapi: 3.0.0
info:
  title: Breathing Space Test Support
  contact: {}
  version: '1.0'
servers:
- url: https://api.service.hmrc.gov.uk/
  description: QA
  variables: {}
paths:
  /test/individuals/breathing-space/single:
    post:
      tags:
      - test
      summary: Add a new Breathing Space Individual document
      description: >
        Add a new Breathing Space Individual document given a non-existing Nino.


        Note that the Nino suffix is removed if included in the "nino" attribute.

        The Nino suffix, if any, can only be provided as "individualDetails"'s attribute.
      operationId: AddanewBreathingSpaceIndividualdocument
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/BreathingSpaceIndividualDocuments'
              - example:
                  nino: MZ123456B
            examples:
              examples-1:
                description: '1'
                value:
                  nino: MZ123456B
              examples-2:
                description: '2'
                value:
                  nino: MZ123456B
                  periods:
                  - startDate: 2020-01-01
                    endDate: 2020-02-29
                    pegaRequestTimestamp: 2020-11-13T20:20:39.000Z
                  - startDate: 2020-04-01
                    pegaRequestTimestamp: 2020-11-13T20:20:39.000Z
              examples-3:
                description: '3'
                value:
                  nino: AB049513
                  individualDetails:
                    details:
                      ninoSuffix: B
                      accountStatusType: 0
                      sex: M
                      dateOfEntry: 1978-12-17
                      dateOfBirth: 1975-02-10
                      dateOfBirthStatus: 1
                      dateOfDeath: 2018-08-09
                      dateOfDeathStatus: 2
                      dateOfRegistration: 1976-01-01
                      registrationType: 8
                      adultRegSerialNumber: 25673ASN
                      cesaAgentIdentifier: SDGH/4
                      cesaAgentClientReference: DIGBY JONES
                      permanentTSuffixCaseIndicator: 0
                      currOptimisticLock: 94
                      liveCapacitorInd: 0
                      liveAgentInd: 0
                      ntTaxCodeInd: 0
                      mergeStatus: 0
                      marriageStatusType: 4
                      crnIndicator: 0
                    nameList:
                      name:
                      - nameSequenceNumber: 1
                        nameType: 1
                        titleType: 1
                        requestedName: Mister Thirty Five Characters Exact
                        nameStartDate: 1996-12-28
                        nameEndDate: 2017-03-31
                        otherTitle: MR S F BRAINS
                        honours: BSc, MA, NUMPTY
                        firstForename: BBTESTFIRSTNAME
                        secondForename: CCTESTSECONDNAME
                        surname: AATESTSURNAME
                    addressList:
                      address:
                      - addressSequenceNumber: 2
                        addressSource: 4
                        countryCode: 1
                        addressType: 1
                        addressStatus: 0
                        addressStartDate: 2003-04-30
                        addressEndDate: 2009-12-31
                        addressLastConfirmedDate: 2003-04-30
                        vpaMail: 254
                        deliveryInfo: THROUGH THE LETTERBOX
                        pafReference: NO IDEA
                        addressLine1: 88 TESTING ROAD
                        addressLine2: TESTTOWN
                        addressLine3: TESTREGION
                        addressLine4: TESTAREA
                        addressLine5: TESTSHIRE
                        addressPostcode: XX77 6YY
                    residencyList:
                      residency:
                      - residencySequenceNumber: 12345
                        dateLeavingUK: 2018-07-22
                        dateReturningUK: 2052-04-05
                        residencyStatusFlag: 0
                    indicators:
                      manualCodingInd: 0
                      manualCodingReason: 10
                      manualCodingOther: JUST BECAUSE
                      manualCorrInd: 0
                      manualCorrReason: A MANUAL CODING REASON ... OR TWO
                      additionalNotes: SOME ADDITIONAL NOTES
                      deceasedInd: 1
                      s128Ind: 0
                      noAllowInd: 0
                      eeaCmnwthInd: 0
                      noRepaymentInd: 0
                      saLinkInd: 0
                      noATSInd: 0
                      taxEqualBenInd: 0
                      p2ToAgentInd: 0
                      digitallyExcludedInd: 0
                      bankruptcyInd: 0
                      bankruptcyFiledDate: 2018-04-05
                      utr: 9384/38TEN
                      audioOutputInd: 0
                      welshOutputInd: 0
                      largePrintOutputInd: 0
                      brailleOutputInd: 0
                      specialistBusinessArea: 16
                      saStartYear: 1992/93
                      saFinalYear: '2017'
                      digitalP2Ind: 1
              examples-4:
                description: '4'
                value:
                  nino: AS000015
                  individualDetails:
                    details:
                      dateOfBirth: 1932-07-07
                      crnIndicator: 0
                    nameList:
                      name:
                      - firstForename: Joe
                        secondForename: The Keyboard
                        surname: Zawinul
                  debts:
                  - chargeReference: ETMP ref01
                    chargeDescription: 100 chars long charge description as exist in ETMP
                    chargeAmount: 199999999.11
                    chargeCreationDate: 2001-09-12
                    chargeDueDate: 2001-12-30
                  - chargeReference: ETMP ref02
                    chargeDescription: long charge 02 description as exist in ETMP
                    chargeAmount: 299999999.22
                    chargeCreationDate: 2002-09-12
                    chargeDueDate: 2002-12-30
                    utrAssociatedWithCharge: '1234567890'
              examples-5:
                description: '5'
                value:
                  nino: AS000015
                  individualDetails:
                    details:
                      dateOfBirth: 1932-07-07
                      crnIndicator: 0
                    nameList:
                      name:
                      - firstForename: Joe
                        secondForename: The Keyboard
                        surname: Zawinul
                  periods:
                  - startDate: 2020-01-01
                    endDate: 2020-02-29
                    pegaRequestTimestamp: 2020-11-13T20:20:39.000Z
        required: true
      responses:
        '201':
          description: Created
          headers: {}
          content: {}
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: INVALID_JSON
              examples:
                invalidJson:
                  description: Invalid Json
                  value:
                    code: INVALID_JSON
                invalidNino:
                  description: Invalid Nino
                  value:
                    code: INVALID_NINO
                missingBody:
                  description: Missing Body
                  value:
                    code: MISSING_BODY
        '409':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: CONFLICTING_REQUEST
              examples:
                duplicatedKey:
                  description: The provided Nino is already existing
                  value:
                    code: CONFLICTING_REQUEST
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
  /test/individuals/breathing-space/bulk:
    post:
      tags:
      - test
      summary: Add one or more new Breathing Space Individual documents
      description: >
        Add one or more new Breathing Space Individual documents.


        Note that the Nino suffix, if any, must be provided as "individualDetails"'s attribute.

        The given "nino" attributes must not include the suffix.
      operationId: AddoneormorenewBreathingSpaceIndividualdocuments
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/BreathingSpaceIndividualDocuments1'
              - example:
                  individuals:
                  - nino: AS000001
                    debts:
                    - chargeReference: ETMP ref01
                      chargeDescription: 100 chars long charge description as exist in ETMP
                      chargeAmount: 199999999.11
                      chargeCreationDate: 2001-09-12
                      chargeDueDate: 2001-12-30
                  - nino: AS000002
                    individualDetails:
                      details:
                        ninoSuffix: C
                        dateOfBirth: 1980-01-01
                  - nino: AS000003
                    periods:
                    - startDate: 2020-01-01
                      endDate: 2020-02-29
                      pegaRequestTimestamp: 2020-11-13T20:20:39.000Z
                    - startDate: 2020-04-01
                      pegaRequestTimestamp: 2020-11-13T20:20:39.000Z
                  - nino: AS000004
                    individualDetails:
                      details:
                        ninoSuffix: C
                    periods:
                    - startDate: 2020-01-01
                      endDate: 2020-02-29
                      pegaRequestTimestamp: 2020-11-13T20:20:39.000Z
            examples:
              examples-1:
                description: '1'
                value:
                  individuals:
                  - nino: AS000001
                    debts:
                    - chargeReference: ETMP ref01
                      chargeDescription: 100 chars long charge description as exist in ETMP
                      chargeAmount: 199999999.11
                      chargeCreationDate: 2001-09-12
                      chargeDueDate: 2001-12-30
                  - nino: AS000002
                    individualDetails:
                      details:
                        ninoSuffix: C
                        dateOfBirth: 1980-01-01
                  - nino: AS000003
                    periods:
                    - startDate: 2020-01-01
                      endDate: 2020-02-29
                      pegaRequestTimestamp: 2020-11-13T20:20:39.000Z
                    - startDate: 2020-04-01
                      pegaRequestTimestamp: 2020-11-13T20:20:39.000Z
                  - nino: AS000004
                    individualDetails:
                      details:
                        ninoSuffix: C
                    periods:
                    - startDate: 2020-01-01
                      endDate: 2020-02-29
                      pegaRequestTimestamp: 2020-11-13T20:20:39.000Z
              examples-2:
                description: '2'
                value:
                  individuals:
                  - nino: AS000006
                    individualDetails:
                      details:
                        dateOfBirth: 1954-06-05
                      nameList:
                        name:
                        - firstForename: Peter
                          surname: Erskine
                  - nino: AS000007
                    individualDetails:
                      details:
                        dateOfBirth: 1951-12-01
                      nameList:
                        name:
                        - firstForename: Jaco
                          surname: Pastorius
                      addressList:
                        address:
                        - addressLine1: Heaven
                      residencyList:
                        residency:
                        - residencySequenceNumber: 9999
                          dateLeavingUK: 1987-09-21
        required: true
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpaceIndividualDocuments3'
                - example:
                    successful: 2
                    duplicates: 0
                    errors: 0
              examples:
                examples-1:
                  value:
                    successful: 2
                    duplicates: 0
                    errors: 0
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: INVALID_JSON
              examples:
                invalidJson:
                  description: Invalid Json
                  value:
                    code: INVALID_JSON
                invalidNino:
                  description: Invalid Nino
                  value:
                    code: INVALID_NINO
                missingBody:
                  description: Missing Body
                  value:
                    code: MISSING_BODY
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
  /test/individuals/breathing-space/count:
    get:
      tags:
      - test
      summary: Count of the existing Breathing Space Individual documents
      description: Count of the existing Breathing Space Individual documents.
      operationId: CountoftheexistingBreathingSpaceIndividualdocuments
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpaceIndividualDocuments4'
                - example:
                    count: 4
              example:
                count: 4
      deprecated: false
  /test/individuals/breathing-space/ninos:
    get:
      tags:
      - test
      summary: List of Ninos of all existing Breathing Space Individual documents
      description: List of Ninos of all existing Breathing Space Individual documents.
      operationId: ListofNinosofallexistingBreathingSpaceIndividualdocuments
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpaceIndividualDocuments5'
                - example:
                    ninos:
                    - AS000001
                    - AS000002
                    - AS000007
                    - AS000008
              example:
                ninos:
                - AS000001
                - AS000002
                - AS000007
                - AS000008
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
  /test/individuals/breathing-space/utr/{nino}:
    get:
      tags:
      - test
      summary: Retrieve, if present, the Individual's UTR
      description: Retrieve, if present, the Individual's UTR.
      operationId: Retrieve,ifpresent,theIndividual'sUTR
      parameters:
      - name: nino
        in: path
        description: >-
          National Insurance Number.


          Must conform to the regular expression. Note that the suffix can optionally be included.


          <code>^((?:[ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D ]?$</code>
        required: true
        style: simple
        schema:
          type: string
          example: MZ006526C, MZ006526
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/RetrieveifpresenttheIndividualsUTR'
                - example:
                    utr: '9876543210'
              example:
                utr: '9876543210'
        '204':
          description: ''
          headers: {}
          content: {}
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
  /test/individuals/breathing-space/wipe-all:
    delete:
      tags:
      - test
      summary: Remove all Breathing Space Individual documents
      description: Remove all Breathing Space Individual documents.
      operationId: RemoveallBreathingSpaceIndividualdocuments
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpaceIndividualDocuments6'
                - example:
                    deleted: 6
              example:
                deleted: 6
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
  /test/individuals/breathing-space/{nino}:
    delete:
      tags:
      - test
      summary: Removes all data for that specific Nino (including Underpayments)
      description: Remove the Breathing Space Individual document and Underpayments for this Nino.
      operationId: RemovesalldataforthatspecificNino(includingUnderpayments)
      parameters:
      - name: nino
        in: path
        description: >-
          National Insurance Number.


          Must conform to the regular expression. Note that the suffix can optionally be included.


          <code>^((?:[ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D ]?$</code>
        required: true
        style: simple
        schema:
          type: string
          example: MZ006526C, MZ006526
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpacecodedoutdebts'
                - example:
                    individualsDeleted: 0
                    underpaymentsDeleted: 2
              example:
                individualsDeleted: 0
                underpaymentsDeleted: 2
      deprecated: false
    get:
      tags:
      - test
      summary: Determines if a Breathing Space Individual document exists for the given Nino
      description: Determines if a Breathing Space Individual document exists for the given Nino.
      operationId: DeterminesifaBreathingSpaceIndividualdocumentexistsforthegivenNino
      parameters:
      - name: nino
        in: path
        description: >-
          National Insurance Number.


          Must conform to the regular expression. Note that the suffix can optionally be included.


          <code>^((?:[ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D ]?$</code>
        required: true
        style: simple
        schema:
          type: string
          example: MZ006526C, MZ006526
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpaceIndividualDocuments7'
                - example:
                    exists: true
              example:
                exists: true
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: INVALID_NINO
              examples:
                invalidNino:
                  description: Invalid Nino
                  value:
                    code: INVALID_NINO
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
    put:
      tags:
      - test
      summary: Replace the Individual details for the given Nino
      description: Replace the Individual details for the given Nino.
      operationId: ReplacetheIndividualdetailsforthegivenNino
      parameters:
      - name: nino
        in: path
        description: >-
          National Insurance Number.


          Must conform to the regular expression. Note that the suffix can optionally be included.


          <code>^((?:[ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D ]?$</code>
        required: true
        style: simple
        schema:
          type: string
          example: MZ006526C, MZ006526
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/individualDetails'
              - example:
                  details:
                    ninoSuffix: D
                  nameList:
                    name:
                    - firstForename: Gary
                      surname: Burton
            examples:
              examples-1:
                description: '1'
                value:
                  details:
                    ninoSuffix: D
                  nameList:
                    name:
                    - firstForename: Gary
                      surname: Burton
              examples-2:
                description: '2'
                value:
                  details:
                    dateOfBirth: 1976-12-11
                    crnIndicator: 0
                  nameList:
                    name:
                    - firstForename: Joe
                      secondForename: Keyboards
                      surname: Zawinul
                    - firstForename: Weather
                      surname: Report
        required: true
      responses:
        '204':
          description: No Content
          headers: {}
          content: {}
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: INVALID_JSON
              examples:
                invalidJson:
                  description: Invalid Json
                  value:
                    code: INVALID_JSON
                invalidNino:
                  description: Invalid Nino
                  value:
                    code: INVALID_NINO
                missingBody:
                  description: Missing Body
                  value:
                    code: MISSING_BODY
        '404':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: RESOURCE_NOT_FOUND
              examples:
                resourceNotFound:
                  description: The provided Nino was not found
                  value:
                    code: RESOURCE_NOT_FOUND
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
  /test/individuals/breathing-space/{nino}/{periodId}:
    delete:
      tags:
      - test
      summary: Remove period for a specific Nino
      description: Remove the Breathing Space Individual period and its Underpayments for this Nino.
      operationId: RemoveperiodforaspecificNino
      parameters:
      - name: nino
        in: path
        description: >-
          National Insurance Number.


          Must conform to the regular expression. Note that the suffix can optionally be included.


          <code>^((?:[ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D ]?$</code>
        required: true
        style: simple
        schema:
          type: string
          example: MZ006526C, MZ006526
      - name: periodId
        in: path
        description: >-
          Breathing Space Period Unique Reference


          Must conform to the regular expression


          <code>^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fAF]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$</code>
        required: true
        style: simple
        schema:
          type: string
          example: 7957547e-1619-4f22-82bb-f12138ec2f8b
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpacecodedoutdebts1'
                - example:
                    periodsDeleted: 1
                    underpaymentsDeleted: 2
              example:
                periodsDeleted: 1
                underpaymentsDeleted: 2
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
  /test/individuals/breathing-space/{nino}/{periodId}/codingout/bulk:
    post:
      tags:
      - test
      summary: Add one or more new Breathing Space coded-out underpayments
      description: >
        Add one or more new Breathing Space coded-out underpayments
      operationId: AddoneormorenewBreathingSpacecoded-outunderpayments
      parameters:
      - name: nino
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: periodId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/POSTCodedOutDebtDetailsforIndividualsinBreathingSpace'
              - example:
                  underPayments:
                  - taxYear: '2011'
                    amount: 400.43
                    source: PAYE UP
                  - taxYear: '2020'
                    amount: 100.23
                    source: SA UP
                  - taxYear: '2017'
                    amount: 39334.23
                    source: SA Debt
            examples:
              examples-1:
                description: '1'
                value:
                  underPayments:
                  - taxYear: '2011'
                    amount: 400.43
                    source: PAYE UP
                  - taxYear: '2020'
                    amount: 100.23
                    source: SA UP
                  - taxYear: '2017'
                    amount: 39334.23
                    source: SA Debt
        required: true
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpacecodedoutunderpaymentsresponse'
                - example:
                    success: '10'
                    fails: '0'
              examples:
                examples-1:
                  value:
                    success: '10'
                    fails: '0'
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: INVALID_JSON
              examples:
                invalidJson:
                  description: Invalid Json
                  value:
                    code: INVALID_JSON
                invalidNino:
                  description: Invalid Nino
                  value:
                    code: INVALID_NINO
                missingBody:
                  description: Missing Body
                  value:
                    code: MISSING_BODY
        '409':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: CONFLICTING_REQUEST
              examples:
                duplicatedKey:
                  description: The Underpayments already exist
                  value:
                    code: CONFLICTING_REQUEST
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
  /test/individuals/breathing-space/codingout:
    delete:
      tags:
      - test
      summary: Remove all Breathing Space coded out underpayments
      description: Remove all Breathing Space coded out underpayments
      operationId: RemoveallBreathingSpacecodedoutunderpayments
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpacecodedoutdebts2'
                - example:
                    deleted: 1
              example:
                deleted: 1
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
  /test/individuals/breathing-space/overview:
    get:
      tags:
      - test
      summary: Get an overview of the test data. That is, periods per nino
      description: A table of periods by nino
      operationId: Getanoverviewofthetestdata.Thatis,periodspernino
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BreathingSpaceOverivewofPeriods'
                - example:
                    periodsByNinos:
                    - nino: AS000001
                      periods:
                      - 62b8ef1b-3e3e-4fb2-9fb8-d890109edade
                    - nino: AS000006
                      periods: []
              example:
                periodsByNinos:
                - nino: AS000001
                  periods:
                  - 62b8ef1b-3e3e-4fb2-9fb8-d890109edade
                - nino: AS000006
                  periods: []
      deprecated: false
      security:
        - userRestricted:
            - breathing-space-test-support
components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating userRestricted API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            breathing-space-test-support: Access breathing space
  schemas:
    errorResponse:
      title: errorResponse
      required:
      - code
      type: object
      properties:
        code:
          type: string
    Address:
      title: Address
      type: object
      properties:
        addressSequenceNumber:
          type: integer
          format: int32
        addressSource:
          type: integer
          format: int32
        countryCode:
          type: integer
          format: int32
        addressType:
          type: integer
          format: int32
        addressStatus:
          type: integer
          format: int32
        addressStartDate:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        addressEndDate:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        addressLastConfirmedDate:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        vpaMail:
          type: integer
          format: int32
        deliveryInfo:
          type: string
        pafReference:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        addressLine4:
          type: string
        addressLine5:
          type: string
        addressPostcode:
          type: string
    AddressList:
      title: AddressList
      required:
      - address
      type: object
      properties:
        address:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Address'
          description: ''
    BreathingSpacecodedoutdebts:
      title: BreathingSpacecodedoutdebts
      required:
      - individualsDeleted
      - underpaymentsDeleted
      type: object
      properties:
        individualsDeleted:
          type: integer
          format: int32
        underpaymentsDeleted:
          type: integer
          format: int32
      description: Schema of DELETE all coded out debts and individual details response
    BreathingSpacecodedoutdebts1:
      title: BreathingSpacecodedoutdebts1
      required:
      - periodsDeleted
      - underpaymentsDeleted
      type: object
      properties:
        periodsDeleted:
          type: integer
          format: int32
        underpaymentsDeleted:
          type: integer
          format: int32
      description: Schema of DELETE period for individual response
    BreathingSpacecodedoutdebts2:
      title: BreathingSpacecodedoutdebts2
      required:
      - deleted
      type: object
      properties:
        deleted:
          type: integer
          format: int32
      description: Schema of DELETE all coded out debts response
    BreathingSpacecodedoutunderpaymentsresponse:
      title: BreathingSpacecodedoutunderpaymentsresponse
      required:
      - success
      - fails
      type: object
      properties:
        success:
          type: string
        fails:
          type: string
      description: Schema of POST for coded out underpayments response
    BreathingSpaceIndividualDocuments:
      title: BreathingSpaceIndividualDocuments
      required:
      - nino
      type: object
      properties:
        nino:
          pattern: ^(?:[ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D ]?$
          type: string
          description: National Insurance Number
          example: MZ006526C
        individualDetails:
          allOf:
          - $ref: '#/components/schemas/individualDetails'
          - description: Schema of Individual Details
        periods:
          type: array
          items:
            $ref: '#/components/schemas/period'
          description: Schema of Periods
        debts:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/debt'
          description: Schema of Debts
      description: Schema of POST single Individual document request
    BreathingSpaceIndividualDocuments1:
      title: BreathingSpaceIndividualDocuments1
      required:
      - individuals
      type: object
      properties:
        individuals:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/BreathingSpaceIndividualDocuments'
          description: ''
      description: Schema of POST multiple Individual documents request
    BreathingSpaceIndividualDocuments3:
      title: BreathingSpaceIndividualDocuments3
      required:
      - successful
      - duplicates
      - errors
      type: object
      properties:
        successful:
          type: integer
          format: int32
        duplicates:
          type: integer
          format: int32
        errors:
          type: integer
          format: int32
      description: Schema of POST Individual documents response
    BreathingSpaceIndividualDocuments4:
      title: BreathingSpaceIndividualDocuments4
      required:
      - count
      type: object
      properties:
        count:
          type: integer
          format: int32
      description: Schema of Count of all existing Individual Documents response
    BreathingSpaceIndividualDocuments5:
      title: BreathingSpaceIndividualDocuments5
      required:
      - ninos
      type: object
      properties:
        ninos:
          type: array
          items:
            type: string
          description: ''
      description: Schema of List of Ninos of all existing Individual Documents response
    BreathingSpaceIndividualDocuments6:
      title: BreathingSpaceIndividualDocuments6
      required:
      - deleted
      type: object
      properties:
        deleted:
          type: integer
          format: int32
      description: Schema of DELETE all Individual Documents response
    BreathingSpaceIndividualDocuments7:
      title: BreathingSpaceIndividualDocuments7
      required:
      - exists
      type: object
      properties:
        exists:
          type: boolean
      description: Schema of Count of all existing Individual Documents response
    BreathingSpaceOverivewofPeriods:
      title: BreathingSpaceOverivewofPeriods
      required:
      - periodsByNinos
      type: object
      properties:
        periodsByNinos:
          minItems: 0
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/PeriodsByNino'
          description: ''
      description: Schema of List of Periods by Nino response
    debt:
      title: debt
      required:
      - chargeReference
      - chargeDescription
      - chargeAmount
      - chargeCreationDate
      - chargeDueDate
      type: object
      properties:
        chargeReference:
          type: string
        chargeDescription:
          type: string
        chargeAmount:
          type: number
        chargeCreationDate:
          pattern: ^(((20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$
          type: string
          example: 2020-01-25
        chargeDueDate:
          pattern: ^(((20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$
          type: string
          example: 2020-01-25
        utrAssociatedWithCharge:
          type: string
    Details:
      title: Details
      type: object
      properties:
        ninoSuffix:
          type: string
        accountStatusType:
          type: integer
          format: int32
        sex:
          type: string
        dateOfEntry:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        dateOfBirth:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        dateOfBirthStatus:
          type: integer
          format: int32
        dateOfDeath:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        dateOfDeathStatus:
          type: integer
          format: int32
        dateOfRegistration:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        registrationType:
          type: integer
          format: int32
        adultRegSerialNumber:
          type: string
        cesaAgentIdentifier:
          type: string
        cesaAgentClientReference:
          type: string
        permanentTSuffixCaseIndicator:
          type: integer
          format: int32
        currOptimisticLock:
          type: integer
          format: int32
        liveCapacitorInd:
          type: integer
          format: int32
        liveAgentInd:
          type: integer
          format: int32
        ntTaxCodeInd:
          type: integer
          format: int32
        mergeStatus:
          type: integer
          format: int32
        marriageStatusType:
          type: integer
          format: int32
        crnIndicator:
          type: integer
          format: int32
    Indicators:
      title: Indicators
      type: object
      properties:
        manualCodingInd:
          type: integer
          format: int32
        manualCodingReason:
          type: integer
          format: int32
        manualCodingOther:
          type: string
        manualCorrInd:
          type: integer
          format: int32
        manualCorrReason:
          type: string
        additionalNotes:
          type: string
        deceasedInd:
          type: integer
          format: int32
        s128Ind:
          type: integer
          format: int32
        noAllowInd:
          type: integer
          format: int32
        eeaCmnwthInd:
          type: integer
          format: int32
        noRepaymentInd:
          type: integer
          format: int32
        saLinkInd:
          type: integer
          format: int32
        noATSInd:
          type: integer
          format: int32
        taxEqualBenInd:
          type: integer
          format: int32
        p2ToAgentInd:
          type: integer
          format: int32
        digitallyExcludedInd:
          type: integer
          format: int32
        bankruptcyInd:
          type: integer
          format: int32
        bankruptcyFiledDate:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        utr:
          type: string
        audioOutputInd:
          type: integer
          format: int32
        welshOutputInd:
          type: integer
          format: int32
        largePrintOutputInd:
          type: integer
          format: int32
        brailleOutputInd:
          type: integer
          format: int32
        specialistBusinessArea:
          type: integer
          format: int32
        saStartYear:
          type: string
        saFinalYear:
          type: string
        digitalP2Ind:
          type: integer
          format: int32
    individualDetails:
      title: individualDetails
      type: object
      properties:
        details:
          $ref: '#/components/schemas/Details'
        nameList:
          $ref: '#/components/schemas/NameList'
        addressList:
          $ref: '#/components/schemas/AddressList'
        residencyList:
          $ref: '#/components/schemas/ResidencyList'
        indicators:
          $ref: '#/components/schemas/Indicators'
      description: Schema of Individual Details
    Name:
      title: Name
      type: object
      properties:
        nameSequenceNumber:
          type: integer
          format: int32
        nameType:
          type: integer
          format: int32
        titleType:
          type: integer
          format: int32
        requestedName:
          type: string
        nameStartDate:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        nameEndDate:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        otherTitle:
          type: string
        honours:
          type: string
        firstForename:
          type: string
        secondForename:
          type: string
        surname:
          type: string
    NameList:
      title: NameList
      required:
      - name
      type: object
      properties:
        name:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Name'
          description: ''
    period:
      title: period
      required:
      - startDate
      type: object
      properties:
        startDate:
          pattern: ^(((20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$
          type: string
          example: 2020-01-25
        endDate:
          pattern: ^(((20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$
          type: string
          example: 2020-01-25
        pegaRequestTimestamp:
          pattern: ^((((20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))[T](([0-1]{1}[0-9]{1})|([2]{1}[0-3]{1}))(:([0-5]{1}[0-9]{1})){2})\.[0-999]{3}[A-Z]{1}$
          type: string
          example: 2020-12-31T20:19:18.123Z
    PeriodsByNino:
      title: PeriodsByNino
      required:
      - nino
      - periods
      type: object
      properties:
        nino:
          type: string
        periods:
          type: array
          items:
            type: string
          description: ''
    POSTCodedOutDebtDetailsforIndividualsinBreathingSpace:
      title: POSTCodedOutDebtDetailsforIndividualsinBreathingSpace
      required:
      - underPayments
      type: object
      properties:
        underPayments:
          minItems: 0
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/underPayment'
          description: ''
      description: POST Coded Out Debt Details for Individuals in Breathing Space
    Residency:
      title: Residency
      type: object
      properties:
        residencySequenceNumber:
          type: integer
          format: int32
        dateLeavingUK:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        dateReturningUK:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
        residencyStatusFlag:
          type: integer
          format: int32
    ResidencyList:
      title: ResidencyList
      required:
      - residency
      type: object
      properties:
        residency:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Residency'
          description: ''
    RetrieveifpresenttheIndividualsUTR:
      title: RetrieveifpresenttheIndividualsUTR
      required:
      - utr
      type: object
      properties:
        utr:
          type: string
      description: Schema of Retrieve of Individual's UTR response
    underPayment:
      title: underPayment
      required:
      - taxYear
      - amount
      - source
      type: object
      properties:
        taxYear:
          type: string
        amount:
          type: number
        source:
          type: string
tags:
- name: test
  description: ''
